### ISSUE TITLE
Install process crashed my site

### ISSUE THREAD

**Issue by amityweb** [ideal-postcodes/magento#435]
Followed the install process here https://docs.ideal-postcodes.co.uk/docs/integrations/magento#installation

Had various composer errors and ultimately some folders were deleted (var/view_preprocessed/pub/static/vendor and var/view_preprocessed/pub/static/vendor/app) and could not fix these errors and so re-installed from backup. Had a terrible morning. 

I dont know if this is to do with your extension or our Magento site, either way, cant install it.

**Comment by amityweb** [comment]
Its possible the magento site I adopted was a bit messed up, I have had to run the compile and deplot commands several times to overcome folder cant be deleted issues. And chmod certain files. It all worked before, but the compile commands which I can see are quote standard caused problems. I have overcome that but there are still a couple of problems with your code...

1) If you pull from git it created a sub-folder under Ukaddresses called magento. So when you run module:enable, it says it Unknown. I had to move all files from under magento up into Ukaddresses 

2) One reason the site got messed up was our local is en_GB but your commands resulted in en_US files being created, and so our static files were not found. I had to include the locale in the compile command. 

3) Your commands also miss the bin folder, minor point, but being new to Magento I had to find out how to call it. 

So this works for me:

git clone --depth=1 https://github.com/ideal-postcodes/magento.git
Move the files in the magento folder up into Ukaddresses, then continue to run:
bin/magento module:enable Idealpostcodes_Ukaddresssearch
bin/magento setup:upgrade
bin/magento setup:di:compile
bin/magento setup:static-content:deploy -f en_GB

**Comment by amityweb** [comment]
But now I get this:

Idealpostcodes_Ukaddresssearch data: current version - none, required version - 3.0.0 {"report_id":"05fabc2b6af555d93b5b8f1afbc7bf05145e1be32f18f91419c35e947172418a","exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): Please upgrade your database: Run \"bin/magento setup:upgrade\" from the Magento root directory.

**Comment by amityweb** [comment]
After changing folder from Ukaddresses to Ukaddresssearch, and running it all again, the error has gone and seems to work.

**Comment by mfilip** [comment]
Hi we are glad that finally you made it work but could you give us more information about your setup like Magento version, some other extensions you installed or maybe some custom modifications in your Magento install. 

Form our side we can now add:

- folder in Magento path should be `/app/code/Idealpostcodes/Ukaddresssearch` and our files from git repository should be copied there (for more clear files structure you need only `etc, Helper, view` folder there and `composer.json, registration.php` files)
- consider to add to your commands `bin/magento setup:perf:generate-fixtures /var/www/html/setup/performance-toolkit/profiles/ce/small.xml` after `bin/magento module:enable Idealpostcodes_Ukaddresssearch`
- `bin/magento setup:static-content:deploy -f en_GB` is right command to setup magento install with targeted locale we provided general command in our docs `bin/magento setup:static-content:deploy -f` which run as default `en_US`

Hope this clear some things around install

We will be glad that when you provide information about your setup to check if we will have same problems with installation you experienced.
